spring:
  application:
    name: aura
  data:
    mongodb:
      uri: mongodb://localhost:27017/aura
      database: aura
  devtools:
    restart:
      enabled: true

server:
  port: 8080

aura:
  events:
    min-interval: 3000
    max-interval: 8000
    history-size: 20